version: "3.9"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - cache:/data
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hotlinebe
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    env_file:
      - .env
    environment:
      RAILS_ENV: development
volumes:
  cache:
    driver: local
